#!/bin/bash

VERSION=1.0-SNAPSHOT

echo "Run Extractor Task ..."
hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Extractor
if [ $? -ne 0 ]
then
	echo "Extractor Task Fail."
	exit 1
fi

echo "Run Analyst Task ..."
hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Analyst
if [ $? -ne 0 ]
then
	echo "Analyst Task Fail."
	exit 1
fi

echo "Run Knitter Task ..."
hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Knitter
if [ $? -ne 0 ]
then
	echo "Knitter Task Fail."
	exit 1
fi

echo "Chart Finished."
exit 0