#!/bin/bash

i=1
while [ $i -le 15 ];
do
	echo "Run Generator Task ..."
	hadoop jar sewing-1.0-SNAPSHOT.jar com.sidooo.sewing.Generator
	if [ $? -ne 0 ] 
	then 
		echo "Generator Task Fail."
		break
	fi
	
	echo "Run Crawl Task ..."
	hadoop jar sewing-1.0-SNAPSHOT.jar com.sidooo.sewing.Crawl
	if [ $? -ne 0 ]
	then 
		echo "Crawk Task Fail."
		break;
	fi
	
	((i++));
done
 