#!/bin/bash

VERSION=1.0-SNAPSHOT

i=1
while [ $i -le 15 ];
do
	echo "Run Generator Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Generator
	if [ $? -ne 0 ] 
	then 
		echo "Generator Task Fail."
		break
	fi
	
	echo "Run Crawl Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Crawl
	if [ $? -ne 0 ]
	then 
		echo "Crawl Task Fail."
		break;
	fi
	
	echo "Run Count Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Counter
	if [ $? -ne 0 ]
	then 
		echo "Counter Task Fail."
		break;
	fi
	
	((i++));
done
 