#!/bin/bash

usage()
{
	echo -e "Usage: `basename $0` -r round [-h]\n";
	exit 1
}

ROUND=0
EXTRACT=0

ARG=`getopt r:eh $*`

set --$ARG;

while getopts r:eh PARAM_VAL
do
	case $PARAM_VAL in
	r)
		ROUND=$OPTARG;
		;;
	e)
		EXTRACT=1
		;;
	h|help)
		usage
		;;
	*)
		;;
	esac
done

if [ $ROUND -eq 0 ]; then
	usage
fi

VERSION=1.0-SNAPSHOT

i=0
while [ $i -lt $ROUND ];
do
	echo "Crawl Round $(($i+1))"
	
	echo "Run Generator Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Generator
	if [ $? -ne 0 ] 
	then 
		echo "Generator Task Fail."
		exit 1
	fi
	
	echo "Run Crawl Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Crawl
	if [ $? -ne 0 ]
	then 
		echo "Crawl Task Fail."
		exit 1
	fi
	
	echo "Run Count Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Counter
	if [ $? -ne 0 ]
	then 
		echo "Counter Task Fail."
		exit 1
	fi
	
	((i++));
done

if [ $EXTRACT -eq 1 ]
then
	echo "Run Extractor Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.HbaseExtractor
	if [ $? -ne 0 ]
	then
		echo "Extractor Task Fail."
		exit 1
	fi
fi

exit 0
