#!/bin/bash

usage()
{
	echo -e "Usage: `basename $0` -r round [-h]\n";
	exit 1
}

ROUND=0

ARG=`getopt r:h $*`

set --$ARG;

while getopts r:h PARAM_VAL
do
	case $PARAM_VAL in
	r)
		ROUND=$OPTARG;
		;;
	h|help)
		usage
		;;
	*)
		;;
	esac
done

if [ $ROUND -eq 0 ]; then
	usage
fi

VERSION=1.0-SNAPSHOT

i=0
while [ $i -lt $ROUND ];
do
	echo "Crawl Round $(($i+1))"
	
	echo "Run Generator Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Generator
	if [ $? -ne 0 ] 
	then 
		echo "Generator Task Fail."
		break
	fi
	
	echo "Run Crawl Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Crawl
	if [ $? -ne 0 ]
	then 
		echo "Crawl Task Fail."
		break;
	fi
	
	echo "Run Count Task ..."
	hadoop jar sewing-$VERSION.jar com.sidooo.sewing.Counter
	if [ $? -ne 0 ]
	then 
		echo "Counter Task Fail."
		break;
	fi
	
	((i++));
done

echo "Run MongoExtractor Task ..."
hadoop jar sewing-$VERSION.jar com.sidooo.sewing.MongoExtractor
if [ $? -ne 0 ]
then
	echo "MongoExtractor Task Fail."
	exit 1
fi
